<?php

namespace Magenest\Test6\Ui\Component\Listing\Grid\Column;

use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class OddOrEven extends Column
{
    /**
     * @param ContextInterface $context
     * @param UiComponentFactory $uiComponentFactory
     * @param array $components
     * @param array $data
     */
    public function __construct(
        ContextInterface   $context,
        UiComponentFactory $uiComponentFactory,
        array              $components = [],
        array              $data = [])
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as &$item) {
                $item['odd_even'] = $item['entity_id'];
                if (isset($item['odd_even'])) {
                    $data = [];
                    if ($item['entity_id'] % 2 == 0) {
                        $data[] = "even";
                    } else {
                        $data[] = "odd";
                    }
                    $item['odd_even'] = $data;
                }
            }
        }
        return $dataSource; // TODO: Change the autogenerated stub
    }

}
