<?php

namespace Magenest\Test6\Ui\Component\Listing\Grid\Column;

use Magento\Framework\View\Element\UiComponent\ContextInterface;
use Magento\Framework\View\Element\UiComponentFactory;
use Magento\Ui\Component\Listing\Columns\Column;

class Rating extends Column
{
    /**
     * @param ContextInterface $context
     * @param UiComponentFactory $uiComponentFactory
     * @param array $components
     * @param array $data
     */
    public function __construct(
        ContextInterface   $context,
        UiComponentFactory $uiComponentFactory,
        array              $components = [],
        array              $data = [])
    {
        parent::__construct($context, $uiComponentFactory, $components, $data);
    }

    public function prepareDataSource(array $dataSource)
    {
        if (isset($dataSource['data']['items'])) {
            foreach ($dataSource['data']['items'] as &$item) {
                if ($item['rating']) {
                    $data = [];
                    for ($i = 0; $i < 5; $i++)
                        if ($i < $item['rating'])
                            $data[] = "rating";
                        else
                            $data[] = 'notStar';

                    $item['rating'] = $data;
                }
            }
        }
        return $dataSource; // TODO: Change the autogenerated stub
    }
}
